language: node_js

node_js:
  - "8"

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -U postgres -c 'create database test;'
  - psql -d test -U postgres -c 'create extension postgis;'